name: Build NX-Activity-Log

on: [push, pull_request, workflow_dispatch]

jobs:
  NX-Activity-Log:
    runs-on: ubuntu-latest
    container: devkitpro/devkita64:latest

    steps:
    - uses: actions/checkout@master
      with:
        submodules: recursive

    - name: Update packages
      run: |
        sudo -n apt-get update
        sudo -n apt-get upgrade -y patch autoconf automake diffutils pkgconf fakeroot git file tar bzip2 zstd

    - name: Silence all git safe directory warnings
      run: git config --system --add safe.directory '*'

    - name: Checkout latest libnx commit
      run: |
        git clone --recurse-submodules https://github.com/switchbrew/libnx.git

    - name: Set workspace permissions
      run: chmod 777 -R "$GITHUB_WORKSPACE"

    - name: Build and install libnx
      run: |
        cd libnx
        make install -j$(nproc)

    - name: Build NX-Activity-Log
      run: |
        make -j$(nproc)

    - uses: actions/upload-artifact@master
      with:
        name: NX-Activity-Log
        path: sdcard/switch/NX-Activity-Log/NX-Activity-Log.nro
        if-no-files-found: error
